#!/usr/bin/env python3
"""Generate Marlin kernel instantiations for the standalone `marlin_tune` build.

This replaces vLLM's csrc/.../marlin/generate_kernels.py.  Differences:

  * Only the (a_type, b_type, c_type) combinations we care about on sm86 are
    emitted:  bf16 activation x {uint4b8, uint8b128} weight x bf16 output.
    That keeps the build to minutes instead of hours.
  * The small-batch path (thread_m_blocks <= 1, i.e. M <= 16) is instantiated
    over an *extended* grid of (thread_k, thread_n, threads) x stages so the
    host code can pick any of them at runtime via marlin_tune.set_config().
  * Output is sharded over several .cu files so nvcc can compile in parallel.

Tile-shape invariant
--------------------
Every stock vLLM tile config satisfies

    threads == thread_k * thread_n / 64

which is exactly the condition that makes the kernel's internal
`b_sh_wr_iters` equal 2 and `warp_rows` equal thread_k/32.  We only generate
configs that satisfy it, because deviating changes the kernel's internal
warp/k-slice indexing in ways the template does not guard with static_asserts
(a wrong choice would silently corrupt results or hang the GPU).
"""

import argparse
import glob
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

FILE_HEAD_COMMENT = """// auto generated by gen_kernels.py
// clang-format off
"""

FILE_HEAD = (
    FILE_HEAD_COMMENT
    + """
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {
"""
)

# (thread_k, thread_n) -> threads is derived.  thread_n <= max_thread_n (256)
# and thread_k/thread_n >= min_thread_k/n (64).
STOCK_TILES = [(128, 128), (64, 256), (64, 128), (128, 64)]

TUNE_TILES = [
    (64, 128),    # stock small-batch #2
    (64, 256),    # stock large-batch #1
    (128, 64),    # stock small-batch #3
    (128, 128),   # stock small-batch #1  <- what M<=16 actually uses today
    (128, 256),
    (256, 64),
    (256, 128),
    (256, 256),
    (512, 64),
    (512, 128),
]

TUNE_STAGES = [2, 3, 4, 5, 6]

# thread_m_blocks: 0.5 means the m_block_size_8 variant (M <= 8).
SMALL_M_BLOCKS = [0.5, 1]
LARGE_M_BLOCKS = [2, 3, 4]

A_TYPE = "kBFloat16"
C_TYPE = "kBFloat16"
S_TYPE = "kBFloat16"
B_TYPES = ["kU4B8", "kU8B128"]

# group_size 128 -> group_blocks 8 (what the Qwen3.8 W4A16 checkpoint uses for
# both the int4 body and the int8 lm_head/embed).  -1 == channelwise; 2 and 4
# are group_size 32 and 64, emitted so the extension is a drop-in for any
# bf16-activation GPTQ checkpoint, not just ours.  group_blocks == 0 (act-order
# with is_k_full=False) is NOT emitted -- see README.
TUNE_GROUP_BLOCKS = [8]
COMPAT_GROUP_BLOCKS = [-1, 2, 4, 8]

# W4A8: int8 activations x uint4b8 weights.  This is the
# VLLM_MARLIN_INPUT_DTYPE=int8 path vLLM takes in batch mode.  No
# m_block_size_8 variant exists for it (marlin.cu gates m_block_size_8 on
# a_type.size_bits() == 16), and int8 activations are only supported against
# 4-bit weights ("W8A8-INT8 is not supported by marlin kernel").
INT8_ACT_A_TYPE = "kS8"
INT8_ACT_B_TYPES = ["kU4B8"]
INT8_ACT_M_BLOCKS = [1, 2, 3, 4]


def stages_ok(thread_k, thread_n, group_blocks, stages):
    """Reject (tile, stages) combinations that silently compute garbage.

    When the quantization group spans more than one k-tile
    (group_blocks > thread_k_blocks) the scale fetch advances only once every
    `group_blocks / thread_k_blocks` pipeline steps, so the stage index and the
    scale index only stay in phase if `stages` is a multiple of that ratio.
    Measured on sm86 with group_size=128:

        thread_k=64  (tk_blocks=4, ratio 2): stages 2/4/6 correct,
                                             stages 3/5 WRONG (rel err ~0.4)
        thread_k>=128 (ratio 1)            : all stages correct

    Stock vLLM never hits this because it hardcodes stages=4.
    """
    if group_blocks <= 0:
        return True
    thread_k_blocks = thread_k // 16
    if thread_k_blocks >= group_blocks:
        return True
    ratio = group_blocks // thread_k_blocks
    return stages % ratio == 0


def threads_for(thread_k, thread_n):
    t = thread_k * thread_n // 64
    assert thread_k * thread_n % 64 == 0
    return t


def smem_bytes(thread_k, thread_n, m_blocks, stages, num_bits, group_size=128,
               a_bits=16):
    """Mirror of get_kernel_cache_size() in marlin.cu (no act-order, no zp)."""
    pack_factor = 32 // num_bits
    tb_m = int(max(m_blocks, 1)) * 16
    sh_a = stages * (tb_m * thread_k) * (1 if a_bits == 8 else 2)
    sh_b = stages * (thread_k * thread_n // pack_factor) * 4
    sh_red = tb_m * (thread_n + 8) * 2
    sh_bias = thread_n * 2
    tmp = min(sh_b, sh_red) + sh_bias
    tmp = max(max(sh_b, sh_red), tmp)
    tb_groups = 1 if group_size == -1 else -(-thread_k // group_size)
    sh_s = tb_groups * thread_n * 2 * stages
    return tmp + sh_a + sh_s


def build_config_set(max_smem):
    """Return an ordered, de-duplicated list of instantiation dicts."""
    seen = set()
    out = []

    def add(b_type, group_blocks, m_blocks, thread_k, thread_n, stages,
            a_type=A_TYPE):
        threads = threads_for(thread_k, thread_n)
        if threads < 128 or threads > 1024:
            return
        if not stages_ok(thread_k, thread_n, group_blocks, stages):
            return
        num_bits = 4 if b_type == "kU4B8" else 8
        gs = 128 if group_blocks > 0 else -1
        a_bits = 8 if a_type == "kS8" else 16
        if smem_bytes(thread_k, thread_n, m_blocks, stages, num_bits, gs,
                      a_bits) > max_smem:
            return
        key = (a_type, b_type, group_blocks, m_blocks, thread_k, thread_n,
               threads, stages)
        if key in seen:
            return
        seen.add(key)
        out.append(
            dict(
                a_type=a_type,
                b_type=b_type,
                c_type=C_TYPE,
                s_type=S_TYPE,
                threads=threads,
                thread_m_blocks=int(max(m_blocks, 1)),
                thread_n_blocks=thread_n // 16,
                thread_k_blocks=thread_k // 16,
                m_block_size_8="true" if m_blocks == 0.5 else "false",
                stages=stages,
                group_blocks=group_blocks,
                is_zp_float="false",
            )
        )

    # 1. extended tuning grid for the small-batch path
    for b_type in B_TYPES:
        for gb in TUNE_GROUP_BLOCKS:
            for m_blocks in SMALL_M_BLOCKS:
                for (tk, tn) in TUNE_TILES:
                    for stages in TUNE_STAGES:
                        add(b_type, gb, m_blocks, tk, tn, stages)

    # 2. stock configs (stages=4) for every m_blocks / group_blocks, so the
    #    extension stays a drop-in replacement for the shapes vLLM would use.
    #    STOCK_TILES covers both small_batch_thread_configs and
    #    large_batch_thread_configs from marlin.cu, so prefill (thread_m_blocks
    #    2..4) resolves to exactly the kernel stock would have picked.
    for b_type in B_TYPES:
        for gb in COMPAT_GROUP_BLOCKS:
            for m_blocks in SMALL_M_BLOCKS + LARGE_M_BLOCKS:
                for (tk, tn) in STOCK_TILES:
                    add(b_type, gb, m_blocks, tk, tn, 4)

    # 3. W4A8 (int8 activation x uint4b8 weight), stock configs at stages=4.
    for b_type in INT8_ACT_B_TYPES:
        for gb in COMPAT_GROUP_BLOCKS:
            for m_blocks in INT8_ACT_M_BLOCKS:
                for (tk, tn) in STOCK_TILES:
                    add(b_type, gb, m_blocks, tk, tn, 4,
                        a_type=INT8_ACT_A_TYPE)

    return out


def template_args(cfg):
    return (
        "vllm::{a}.id(), vllm::{b}.id(), vllm::{c}.id(), vllm::{s}.id(), "
        "{threads}, {tmb}, {tnb}, {tkb}, {m8}, {stages}, {gb}, {zpf}".format(
            a=cfg["a_type"],
            b=cfg["b_type"],
            c=cfg["c_type"],
            s=cfg["s_type"],
            threads=cfg["threads"],
            tmb=cfg["thread_m_blocks"],
            tnb=cfg["thread_n_blocks"],
            tkb=cfg["thread_k_blocks"],
            m8=cfg["m_block_size_8"],
            stages=cfg["stages"],
            gb=cfg["group_blocks"],
            zpf=cfg["is_zp_float"],
        )
    )


def selector_conditions(cfg):
    return " && ".join(
        [
            "a_type == vllm::{}".format(cfg["a_type"]),
            "b_type == vllm::{}".format(cfg["b_type"]),
            "c_type == vllm::{}".format(cfg["c_type"]),
            "s_type == vllm::{}".format(cfg["s_type"]),
            "threads == {}".format(cfg["threads"]),
            "thread_m_blocks == {}".format(cfg["thread_m_blocks"]),
            "thread_n_blocks == {}".format(cfg["thread_n_blocks"]),
            "thread_k_blocks == {}".format(cfg["thread_k_blocks"]),
            "m_block_size_8 == {}".format(cfg["m_block_size_8"]),
            "stages == {}".format(cfg["stages"]),
            "group_blocks == {}".format(cfg["group_blocks"]),
            "is_zp_float == {}".format(cfg["is_zp_float"]),
        ]
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=HERE)
    ap.add_argument("--shards", type=int, default=16)
    ap.add_argument(
        "--max-smem",
        type=int,
        default=101376 - 512,
        help="max dynamic shared mem per block (sm86 = 99KB)",
    )
    ap.add_argument("--stock-only", action="store_true",
                    help="emit only the 4 stock tiles at stages=4 (fast build)")
    args = ap.parse_args()

    if args.stock_only:
        global TUNE_TILES, TUNE_STAGES
        TUNE_TILES = STOCK_TILES
        TUNE_STAGES = [4]

    for f in glob.glob(os.path.join(args.out_dir, "mt_kernel_*.cu")):
        os.remove(f)
    sel = os.path.join(args.out_dir, "kernel_selector.h")
    if os.path.exists(sel):
        os.remove(sel)

    cfgs = build_config_set(args.max_smem)

    shards = [[] for _ in range(args.shards)]
    for i, cfg in enumerate(cfgs):
        shards[i % args.shards].append(cfg)

    n_files = 0
    for i, shard in enumerate(shards):
        if not shard:
            continue
        body = "\n\n".join(
            "template __global__ void Marlin<{}>( MARLIN_KERNEL_PARAMS );".format(
                template_args(c)
            )
            for c in shard
        )
        with open(os.path.join(args.out_dir, "mt_kernel_%02d.cu" % i), "w") as f:
            f.write(FILE_HEAD + "\n\n" + body + "\n\n}\n")
        n_files += 1

    lines = [FILE_HEAD_COMMENT]
    for i, cfg in enumerate(cfgs):
        kw = "if" if i == 0 else "else if"
        lines.append(
            "%s (%s)\n  kernel = Marlin<%s>;\n"
            % (kw, selector_conditions(cfg), template_args(cfg))
        )
    with open(sel, "w") as f:
        f.write("".join(lines))

    print(
        "gen_kernels: %d instantiations over %d files -> %s"
        % (len(cfgs), n_files, args.out_dir),
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
